
export const EXPORT_DATA_TYPE = 'TYPE';
export const EXPORT_DATA_VALUE = 'VALUE';
export const EXPORT_DATA_KEY = 'KEY';

//TODO: RENAME
export const NOTION_RESULT_SUCCESS = 'NOTION_RESULT_SUCCESS';
export const NOTION_RESULT_ERROR = 'NOTION_RESULT_ERROR';
export const NOTION_RESULT = 'NOTION_RESULT';

export const NOTION_RESULT_PRIMARY_DATABASE = 'NOTION_RESULT_PRIMARY_DATABASE';
export const NOTION_RESULT_RELATION_DATABASES = 'NOTION_RESULT_RELATION_DATABASES';
export const NOTION_RESULT_DATABASE_ID = 'NOTION_RESULT_DATABASE_ID';
export const NOTION_RESULT_BLOCKS = 'NOTION_RESULT_BLOCKS';

export const NOTION_RESULT_BLOCK_KEY = 'NOTION_RESULT_BLOCK_KEY';
export const NOTION_RESULT_BLOCK_DBS = 'NOTION_RESULT_BLOCK_DBS';
export const URL_SEARCH_PARAM_DATABASE = 'd';
export const URL_SEARCH_PARAM_BLOCKS_REQUEST = 'b';
export const URL_SEARCH_PARAM_RELATIONS_REQUEST = 'r';
