
export const EXPORT_DATA_TYPE = 'TYPE';
export const EXPORT_DATA_VALUE = 'VALUE';
export const EXPORT_DATA_KEY = 'KEY';
export const EXPORT_DATA_PROPERTIES = 'PROPERTIES';
export const EXPORT_DATA_METADATA = 'METADATA';

export const NOTION_RESULT_SUCCESS = 'NOTION_RESULT_SUCCESS';
export const NOTION_RESULT_ERROR = 'NOTION_RESULT_ERROR';
export const NOTION_RESULT = 'NOTION_RESULT';

export const NOTION_RESULT_PRIMARY_DATABASE = 'NOTION_RESULT_PRIMARY_DATABASE';
export const NOTION_RESULT_RELATION_DATABASES = 'NOTION_RESULT_RELATION_DATABASES';
export const NOTION_RESULT_DATABASE_ID = 'NOTION_RESULT_DATABASE_ID';
export const NOTION_RESULT_DATABASE_TITLE = 'NOTION_RESULT_DATABASE_TITLE';
export const NOTION_RESULT_PARENT_TITLE = 'NOTION_RESULT_PARENT_TITLE';
export const NOTION_RESULT_PARENT_ID = 'NOTION_RESULT_PARENT_ID';
export const NOTION_RESULT_PARENT_TYPE = 'NOTION_RESULT_PARENT_TYPE';
export const NOTION_RESULT_BLOCKS = 'NOTION_RESULT_BLOCKS';
export const NOTION_RESULT_COLUMN_LISTS = 'NOTION_RESULT_COLUMN_LISTS';
export const NOTION_RESULT_PAGE_DATA = 'NOTION_RESULT_PAGE_DATA';
export const NOTION_RESULT_ICON = 'NOTION_RESULT_ICON';
export const NOTION_RESULT_COVER = 'NOTION_RESULT_COVER';

export const NOTION_RESULT_RELATION_DATABASE_ID = 'DATABASE_ID';
export const NOTION_RESULT_RELATION_BLOCK_ID = 'BLOCK_ID';
export const NOTION_RESULT_RELATION_PAGE_ID = 'PAGE_ID';

export const NOTION_RESULT_BLOCK_KEY = 'NOTION_RESULT_BLOCK_KEY';
export const NOTION_RESULT_BLOCK_DBS = 'NOTION_RESULT_BLOCK_DBS';
export const URL_SEARCH_PARAM_DATABASE = 'd';
export const URL_SEARCH_PARAM_BLOCKS_REQUEST = 'b';
export const URL_SEARCH_PARAM_RELATIONS_REQUEST = 'r';
export const URL_SEARCH_PARAM_PAGE_CURSOR_TYPE_REQUEST = 'c';
export const URL_SEARCH_PARAM_PAGE_CURSOR_ID_REQUEST = 'i';

export const URL_PAGE_CURSOR_TYPE_ALL = 'a';
export const URL_PAGE_CURSOR_TYPE_SPECIFIC = 's';
export const URL_PAGE_CURSOR_TYPE_DEFAULT = 'd';