export const NOTION_WRANGLE_KEY_RELATIONS_MAP = 'NOTION_WRANGLE_KEY_RELATIONS_MAP';
export const NOTION_WRANGLE_KEY_DATA_DB_MAP = 'NOTION_WRANGLE_KEY_DATA_DB_MAP';
export const NOTION_WRANGLE_KEY_TITLES_MAP = 'NOTION_WRANGLE_KEY_TITLES_MAP';

export const NOTION_RESULT_BLOCK_DBS = 'NOTION_RESULT_BLOCK_DBS';
export const NOTION_RESULT_BLOCK_KEY = 'NOTION_RESULT_BLOCK_KEY';
export const NOTION_RESULT_COLUMN_LISTS = 'NOTION_RESULT_COLUMN_LISTS';